2024-11-01 02:40:07,320 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\PythonProject\Urban\tests_12_4.py", line 22, in test_run
    r = Runner(5)
        ^^^^^^^^^
  File "D:\PythonProject\Urban\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-01 02:40:07,321 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PythonProject\Urban\tests_12_4.py", line 12, in test_walk
    r = Runner('Pygirl', -5)
        ^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\Urban\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
